env:
  node: true
  commonjs: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 12

rules:
  no-console: off
  import/extensions:
    - error
    - always
  import/no-dynamic-require: off
  global-require: off