name: Deploy to Remote Server
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: SSH and deploy
      uses: appleboy/ssh-action@v1.0.3  
      with:
        host: ${{ secrets.SERVER_HOST }}  
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/discordBot_JS  # Переходим в директорию проекта 
          git pull origin main  # Подтягиваем изменения с главной ветки
          touch .env
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
          nohup bash ../deploy.sh > bot.log 2>&1 &
